services:
  db:
    image: mariadb:10.11
    container_name: facturas_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: bill_soft
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  server:
    build:
      context: ./server
    container_name: facturas_server
    volumes:
      - ./server:/usr/src/app
      - ./server/logs:/usr/src/app/logs
      - server_node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASS=12345
      - DB_NAME=bill_soft
    depends_on:
      - db

  client:
    build:
      context: ./client
    container_name: facturas_client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4200:4200"
    command: npm run start -- --host 0.0.0.0 --poll 2000
    depends_on:
      - server

volumes:
  mariadb_data:
  server_node_modules: